// Code generated by ent, DO NOT EDIT.

package ent

import (
	"simple_sns_api/ent/post"
	"simple_sns_api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescBody is the schema descriptor for body field.
	postDescBody := postFields[0].Descriptor()
	// post.DefaultBody holds the default value on creation for the body field.
	post.DefaultBody = postDescBody.Default.(string)
}
