// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomUser is the predicate function for roomuser builders.
type RoomUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
